language: cpp
os: linux
compiler: clang

sudo: required
dist: trusty     

before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
    - sudo apt-get update -qq
    
install:
    - sudo apt-get --yes install qt510base 
    
script:
    - QTDIR="/opt/qt510"
    - PATH="$QTDIR/bin:$PATH"
    - source /opt/qt510/bin/qt510-env.sh

   