language: cpp
os: linux
compiler: clang

sudo: required
dist: trusty   

env:
    - export COVERALLS_SERVICE_NAME=travis-ci
    - export COVERALLS_REPO_TOKEN=KQ14UwDkm2k8cbB4YZS61pL1GECbMPG2V

before_install:
    # Add and update Qt 5.10.1 Repository
    - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
    - sudo apt-get update -qq

    # Coveralls install
    - pip install --user cpp-coveralls

install:
    # Install Qt 5.10.1
    - sudo apt-get --yes install qt510base
    
script:
    # Get the cmake version
    - which cmake
    - cmake --version

    # Setup Qt Variables
    - QTDIR="/opt/qt510"
    - PATH="$QTDIR/bin:$PATH"
    - source /opt/qt510/bin/qt510-env.sh

    # Execute cmake configuration
    - cmake -H. -Bbuild -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=/opt/qt510/lib/cmake

    - cd build

    # Execute the build
    - cmake --build .

    # run tests
    - ctest

    # Upload to coverall
    - make coveralls