language: cpp
os: linux
compiler: clang

sudo: required
dist: trusty     

before_install:
    # Add and update Qt 5.10.1 Repository
    - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
    - sudo apt-get update -qq
    # Coveralls install
    - pip install --user cpp-coveralls
    
install:
    # Install Qt 5.10.1
    - sudo apt-get --yes install qt510base 
    
script:
    # Setup Qt Variables
    - QTDIR="/opt/qt510"
    - PATH="$QTDIR/bin:$PATH"
    - source /opt/qt510/bin/qt510-env.sh

    # Create new build directory
    - cmake -H. -Bbuild
    - cd build

    # build the project
    - cmake --build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/qt510/lib/cmake

    # test the project
    - ctest
after_success:
    - coveralls --exclude test --exclude doc -gcov --gcov-options '\-lp'